### ISSUE TITLE
Visual Studio for Mac loses focus on application switch

### ISSUE THREAD

**Issue by ugultopu** [Microsoft/vs4mac-labs#5]
I'm not sure if this is the right place for this but here we go:

# Version Information
OS: macOS 10.13.1
VS: Visual Studio for Mac, Community Edition, 7.3 (build 799)

# Expected Results
When the user switches to another application using Cmd + Tab, and then re-switches back to VS using Cmd + Tab, the focus should be on the editor and the user should be able to keep on editing without manually bringing the focus to the editor.

# Actual Results
When the user switches to another application using Cmd + Tab, and then re-switches back to VS using Cmd + Tab, the focus is lost from the editor. User is not able to keep on editing without manually bringing the focus to the editor.

# Workaround
After switching back to Visual Studio, press Shift + Tab 2 times.

**Comment by rajenki** [comment]
Hi, please report issues with Visual Studio for Mac through the IDE itself (via the Help -> Report a Problem menu). If you run into issues with the labs, please post them here.
