### ISSUE TITLE
After adding docker support docker-compose is not set as the startup project like in documentation

### ISSUE THREAD

**Issue by gianlazz** [Microsoft/vs4mac-labs#8]
I also had to add in the docker compose.dcproj as an existing project as it wasn't add in on it's own.

I'm on vs4mac 7.5.3 and I'm wondering if this behavior is normal as of some update since the documentation was written or something else?

Update:
Okay so I've created a new project and was able to get the docker-compose project added in and set as the default automatically like in the documentation. I think the problem may have come from my other original solution that I'm having trouble having had been started first as an empty solution that I added in projects to...

**Comment by lisaguthrie** [comment]
Thanks for reporting this. The documentation reflects the current behavior. Glad you were able to get it working!
